flowchart TD
  A[Is UUID in path?] -->|Yes| B[Fetch user by path UUID. Is valid UUID?]
  B -->|Yes| C[Save UUID to localStorage.]
  B -->|No| D[Remove UUID from path.]
  D --> E[Is UUID in localStorage?]

  A -->|No| E

  E -->|Yes| F[Fetch user by localStorage UUID. Is valid UUID?]
  F -->|Yes| G[Set UUID in path.]
  F -->|No| H[Remove UUID from localStorage.]
  H --> I[Create new user.]
  E -->|No| I

  I --> J[Set UUID in path.]
  J --> K[Save UUID to localStorage.]
